### ISSUE TITLE
TextWrap should have an unwrap module.

### ISSUE THREAD

**Issue by sambitdash** [carlobaldassi/TextWrap.jl#5]
Use case:

Sometime data presented may not be rightly wrapped. This will provide a way to rewrap the text again with a new column width.

**Comment by carlobaldassi** [comment]
(Sorry, I missed this)
I don't quite understand: the current `wrap` function already rewraps whatever you give to it. Also, you can unwrap lines by just substituting newlines with spaces, e.g. `replace(text, "\n", " ")` (or, in julia 0.7-DEV, `replace("text", "\n" => " ")`).

Maybe I'm not understanding what you mean by unwrapping?

**Comment by sambitdash** [comment]
I should have been a bit more elaborate. I was looking for emacs fill command like behaviors with undo. 

https://www.gnu.org/software/emacs/manual/html_node/emacs/Fill-Commands.html

But you may not need undo in Julia and you can always keep a copy of the string before wrapping. 

But guess with multiple commands usage one can achieve them. So closing the issue.
